version: "3.0"

services:

  solexiv:
    build:
      context: .
      args:
        DEV_MODE: prototype
        USERNAME: piopy
        USER_UID: 1000
        USER_GID: 1000
    # working_dir: /app/src
    image: solexiv/solexiv
    container_name: solexiv
    environment:
      - SAFEBOX=1
    volumes:
      - ./data:/app/data
      - ./src:/app/src
      - ./creds:/app/creds
    ports:
      - 8181:8181
    restart: 'unless-stopped'
    # command: streamlit run Homepage.py --server.port 8181 --server.address 0.0.0.0 --browser.gatherUsageStats False
    networks:
      - defaultNetwork

networks:
  defaultNetwork:
