version: "3.0"

services:

  solexiv:
    build:
      context: .
      args:
        DEV_MODE: prototype
        USERNAME: ${USER}
        USER_UID: 1000
        USER_GID: 1000
    image: solexiv/solexiv
    container_name: solexiv
    environment:
      - SAFEBOX=0
    volumes:
      - ./data:/app/data
      - ./creds:/app/creds
    ports:
      - 8181:8181
    restart: 'unless-stopped'
    command: streamlit run Homepage.py --server.port 8181 --server.address 0.0.0.0 --browser.gatherUsageStats False
