categorie = [
    "Affitto",
    "Bolletta",
    "Alimentari",
    "Abbigliamento",
    "Stipendio",
    "Finanziamento",
    "Shopping online",
    "Pranzo da asporto",
    "Uscite Serali/Svago",
    "Trasporto",
    "Salute",
    "Prelievo",
    "Ricarica prepagata",
    "Regalo",
    "Altro",
]
